name: Kernel Compilation

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Tag'
        required: true    

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up build environment
      run: |
        sudo apt update -y
        sudo apt install default-jdk git gnupg flex bison gperf build-essential zip curl \
        libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev \
        python3 make sudo gcc g++ bc grep tofrodos python3-markdown libxml2-utils xsltproc \
        zlib1g-dev python-is-python3 libc6-dev libtinfo6 make cpio kmod openssl \
        libelf-dev libssl-dev -y

    - name: Set environment variable
      run: |
        echo "BUILD_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV        

    - name: Compile Kernel
      run: |
        bash build.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KernelSU-Next-SM-M145F-${{ github.event.inputs.tag }}
        path: build/*.tar

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.inputs.tag }}
        name: "KernelSU-Next-SM-M145F-${{ github.event.inputs.tag }}"
        draft: false
        prerelease: false
        token: ${{ secrets.TOKEN }}          
        artifacts: "build/*.tar"
        body: "Commit SHA: ${{ github.sha }}"
